ClearAll was setting an empty list instead of an empty dict in defintions.options.  (#1908)
Mypy didn't detect it. This produced a crash if we apply ClearAll[] to a
symbol, and then we try to evaluate an expression. For example
```
ClearAll[F]; 
F[x_, opt:OptionsPattern[]]:=x^2;
F[32]
```
without this fix, produces an exception:
```

  File "/home/mauricio/Projects/mathics-core/mathics/core/pattern.py", line 1151, in yield_wrapping
    parms["element"].match(
    ~~~~~~~~~~~~~~~~~~~~~~^
        item,
        ^^^^^
    ...<8 lines>...
        },
        ^^
    )
    ^
  File "/home/mauricio/Projects/mathics-core/mathics/builtin/patterns/composite.py", line 342, in match
    for name, value in values.items():
                       ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'items'

```